accounts/urls.py
from django.urls import path

from . import views

app_name = 'accounts'

urlpatterns = [
    path('login', views.login, name='login'),
    path('logout', views.logout, name='logout'),
    path('register', views.register, name='register'),
    path('dashboard', views.dashboard, name='dashboard'),
    path('activate/<uidb64>/<token>/', views.activate, name='activate'),
]

listings/urls.py
from django.urls import path

from . import views

app_name = 'listings'

urlpatterns = [
    path('', views.listings, name='listings'),
    path('<int:listing_id>', views.listing, name='listing'),
    path('search', views.search, name='search')
]

pages/urls.py
from django.urls import path

from . import views

app_name = 'pages'

urlpatterns = [
    path('', views.index, name='index'),
    path('about', views.about, name='about')
]

realestate/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('', include('pages.urls', namespace='pages')),
    path('listings/', include('listings.urls', namespace='listings')),
    path('accounts/', include('accounts.urls', namespace='accounts')),
    path('contacts/', include('contacts.urls', namespace='contacts')),
    path('admin/', admin.site.urls),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

templates/partials/_alerts.html
{% load static %}
{% if messages %}
  {% for message in messages %}
    <div id="message" class="container">
      <div class="alert alert-{{ message.tags }} alert-dismissible text-center fade show" role="alert" id="alert">
        <button type="button" class="close" data-dismiss="alert"><span aria-hidden="true">&times;</span></button>
        <strong>
          {% if message.level == DEFAULT_MESSAGE_LEVELS.ERROR %}
            Error:
          {% else %}
            {{ message.tags | title }}:
          {% endif %}
        </strong>
        {{ message }}
      </div>
    </div>
  {% endfor %}
{% endif %}

templates/partials/_footer.html
<!-- Footer -->
<footer id="main-footer" class="py-4 bg-primary text-white text-center">
    Copyright &copy;
    <span class="year"></span> Lok Real Estate Group
</footer>

templates/partials/_navbar.html
{% load static %}
<!-- Navbar -->
<nav class="navbar navbar-expand-lg navbar-dark bg-primary sticky-top">
    <div class="container">
    <a class="navbar-brand" href="{% url 'pages:index' %}">
        <img src="{% static 'img/logo.png' %}" class="logo" alt="">
    </a>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavAltMarkup">
        <span class="navbar-toggler-icon"></span>
    </button>
        <div class="collapse navbar-collapse" id="navbarNavAltMarkup">
            <ul class="navbar-nav">
                <li class="nav-item {% if '/' == request.path %} active {% endif %} mr-3">
                    <a class="nav-link" href="{% url 'pages:index' %}">Home</a>
                </li>
                <li class="nav-item {% if 'about' in request.path %} active {% endif %} mr-3">
                    <a class="nav-link" href="{% url 'pages:about' %}">About</a>
                </li>
                <li class="nav-item {% if 'listings' in request.path %} active {% endif %} mr-3">
                    <a class="nav-link" href="{% url 'listings:listings' %}">Featured Listings</a>
                </li>
            </ul>

            <ul class="navbar-nav ml-auto">
                {% if request.user.is_authenticated %}
                    <li class="nav-item {% if 'dashboard' in request.path %} active {% endif %} mr-3">
                        <a class="nav-link" href="{% url 'accounts:dashboard' %}">
                        <i class="fas fa-user"></i> {{ request.user.username }}</a>
                    </li>
                    <li class="nav-item mr-3">
                        <a class="nav-link" href="javascript:{document.getElementById('logout').submit()}">
                        <i class="fas fa-sign-out-alt"></i> Logout</a>
                        <form action="{% url 'accounts:logout' %}" method="POST" id="logout">
                            {% csrf_token %}
                            <input type="hidden">
                        </form>
                    </li>
                {% else %}
                    <li class="nav-item {% if 'register' in request.path %} active {% endif %} mr-3">
                        <a class="nav-link" href="{% url 'accounts:register' %}">
                        <i class="fas fa-user-plus"></i> Register</a>
                    </li>
                    <li class="nav-item {% if 'login' in request.path %} active {% endif %} mr-3">
                        <a class="nav-link" href="{% url 'accounts:login' %}">
                        <i class="fas fa-sign-in-alt"></i> Login</a>
                    </li>
                {% endif %}
            </ul>
        </div>
    </div>
</nav>

templates/partials/_topbar.html
<!-- Top Bar -->
<section id="top-bar" class="p-3">
    <div class="container">
        <div class="row">
            <div class="col-md-4">
                <i class="fas fa-phone"></i> (832)-638-2222
            </div>
            <div class="col-md-4">
                <i class="fas fa-envelope-open"></i> loklok12614@gmail.com
            </div>
            <div class="col-md-4">
                <div class="social text-right">
                    <a href="#">
                        <i class="fab fa-twitter"></i>
                    </a>
                    <a href="#">
                        <i class="fab fa-facebook"></i>
                    </a>
                    <a href="#">
                        <i class="fab fa-linkedin"></i>
                    </a>
                    <a href="#">
                        <i class="fab fa-instagram"></i>
                    </a>
                    <a href="#">
                        <i class="fab fa-pinterest"></i>
                    </a>
                </div>
            </div>
        </div>
    </div>
</section>