accounts/urls.py
from django.urls import path

from . import views

app_name = 'accounts'

urlpatterns = [
    path('login', views.login, name='login'),
    path('logout', views.logout, name='logout'),
    path('register', views.register, name='register'),
    path('dashboard', views.dashboard, name='dashboard'),
    path('activate/<uidb64>/<token>/', views.activate, name='activate'),
]

listings/urls.py
from django.urls import path

from . import views

app_name = 'listings'

urlpatterns = [
    path('', views.listings, name='listings'),
    path('<int:listing_id>', views.listing, name='listing'),
    path('search', views.search, name='search')
]

pages/urls.py
from django.urls import path

from . import views

app_name = 'pages'

urlpatterns = [
    path('', views.index, name='index'),
    path('about', views.about, name='about')
]

realestate/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('', include('pages.urls', namespace='pages')),
    path('listings/', include('listings.urls', namespace='listings')),
    path('accounts/', include('accounts.urls', namespace='accounts')),
    path('contacts/', include('contacts.urls', namespace='contacts')),
    path('admin/', admin.site.urls),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

accounts/models.py
from django.db import models

accounts/forms.py
from django import forms  
from django.contrib.auth.forms import UserCreationForm  
from django.contrib.auth.models import User  
  
class RegistrationForm(UserCreationForm):  
    email = forms.EmailField(max_length=200, help_text='Required')  
    class Meta:  
        model = User  
        fields = ('first_name', 'last_name', 'username', 'email', 'password1', 'password2')  

accounts/views.py
from django.http import HttpResponse
from django.shortcuts import render, redirect
from django.contrib import messages, auth
from django.contrib.auth.models import User
from django.core.mail import EmailMessage
from contacts.models import Contact

from django.contrib.auth.decorators import login_required
from django.contrib.auth import login, authenticate, get_user_model
from django.contrib.sites.shortcuts import get_current_site
from django.utils.encoding import force_bytes, force_text  
from django.utils.http import urlsafe_base64_encode, urlsafe_base64_decode  
from django.template.loader import render_to_string
from django.core.exceptions import ObjectDoesNotExist

from .token import account_activation_token

# Create your views here.
# def register(request):
#     if request.method == "POST":
#         #Get form 
        # first_name = request.POST['first_name']
        # last_name = request.POST['last_name']
        # username = request.POST['username']
        # email = request.POST['email']
        # password = request.POST['password']
        # password2 = request.POST['password2']
        # error = False

        # # Check username
        # if User.objects.filter(username=username):
        #     error = True
        #     messages.error(request, 'Username has been taken')
        # # Check email
        # if User.objects.filter(email=email):
        #     error = True
        #     messages.error(request, 'Email address already in use')
        # # Check if passwords match
        # if password != password2:
        #     error = True
        #     messages.error(request, 'Passwords do not match')
#         if error is False:
#             # Create user
            # user = User.objects.create_user(username=username, email=email, password=password, 
            #                             first_name=first_name, last_name=last_name)
#             #Login after register
#             # auth.login(request, user)
#             # messages.success(request, f'Welcome {user.username}!')
#             # return redirect('pages:index')

#             user.save()
#             messages.success(request, 'You are now registered and can login')
#             return redirect('accounts:login')
#         return redirect('accounts:register')
#     else:
#         return render(request, 'accounts/register.html')

# Register V.2 (Email Verification required)
def register(request):
    if request.user.is_authenticated:
        return redirect('pages:index')
    if request.method == 'POST':
        first_name = request.POST['first_name']
        last_name = request.POST['last_name']
        username = request.POST['username']
        email = request.POST['email']
        password = request.POST['password']
        password2 = request.POST['password2']
        error = False

        # Check username
        if User.objects.filter(username=username):
            error = True
            messages.error(request, 'Username has been taken')
        # Check email
        if User.objects.filter(email=email):
            error = True
            messages.error(request, 'Email address already in use')
        # Check if passwords match
        if password != password2:
            error = True
            messages.error(request, 'Passwords do not match')

        if error == False:
            user = User.objects.create_user(username=username, email=email, password=password, 
                                        first_name=first_name, last_name=last_name)
            user.is_active = False
            user.save()

            current_site = get_current_site(request)
            mail_subject = 'Activation link has been sent to your email id'
            message = render_to_string('accounts/acc_active_email.html', {
                'user': user,
                'domain': current_site.domain,
                'uid':urlsafe_base64_encode(force_bytes(user.pk)),
                'token':account_activation_token.make_token(user),
            })
            to_email = email
            email = EmailMessage(
                mail_subject, message, to=[to_email], from_email="loksdjango@gmail.com"
            )
            email.send()
            messages.success(request, 'Please confirm your email address to complete the registration')
            return redirect('pages:index')
        return redirect('accounts:register')
    return render(request, 'accounts/register.html')

def login(request):
    if request.method == "POST":
        username = request.POST['username']
        password = request.POST['password']
        error = False

        try:
            user = User.objects.get(username=username)
            if not user.is_active:
                error = True
                messages.error(request, 'Registration not complete, please check your inbox for verification email.')
                return redirect('accounts:login')
            if user is not None and error is False:
                auth_user = auth.authenticate(username=username, password=password)
                auth.login(request, auth_user)
                messages.success(request, 'You are now logged in')
                return redirect('pages:index')
            else:
                messages.error(request, 'Invalid Credentials')
                return redirect('accounts:login')
        except ObjectDoesNotExist:
            messages.error(request, 'Invalid Credentials')
            return redirect('accounts:login')
    else:
        return render(request, 'accounts/login.html')

def logout(request):
    if request.method == "POST":
        auth.logout(request)
        messages.success(request, 'You are now logged out')
    return redirect('pages:index')

@login_required(login_url='accounts:login')
def dashboard(request):
    user_contacts = Contact.objects.order_by('-contact_date').filter(user_id=request.user.id)
    context = {
        'contacts': user_contacts,
    }
    return render(request, 'accounts/dashboard.html', context)

def activate(request, uidb64, token):
    User = get_user_model()
    try:
        uid = force_text(urlsafe_base64_decode(uidb64))
        user = User.objects.get(pk=uid)
    except(TypeError, ValueError, OverflowError, User.DoesNotExist):
        user = None
    if user is not None and account_activation_token.check_token(user, token):
        user.is_active = True
        user.save()
        messages.success(request, 'Thank you for your email confirmation. Now you can login your account.')
        return redirect('pages:index')
    else:  
        messages.error(request, 'Activation link is invalid!')
        return redirect('pages:index') 

templates/accounts/acc_active_email.html
{% autoescape off %}  
Hi {{ user.username }},  
Please click on the link to confirm your registration,  
http://{{ domain }}{% url 'accounts:activate' uidb64=uid token=token %}  
{% endautoescape %} 

templates/accounts/dashboard.html
{% extends 'base.html' %}

{% block title %}| User Dashboard{% endblock %}

{% block content %}
  <section id="showcase-inner" class="py-5 text-white">
    <div class="container">
      <div class="row text-center">
        <div class="col-md-12">
          <h1 class="display-4">User Dashboard</h1>
          <p class="lead">Manage your BT Real Estate account</p>
        </div>
      </div>
    </div>
  </section>

  <!-- Breadcrumb -->
  <section id="bc" class="mt-3">
    <div class="container">
      <nav aria-label="breadcrumb">
        <ol class="breadcrumb">
          <li class="breadcrumb-item">
            <a href="{% url 'pages:index' %}">
              <i class="fas fa-home"></i> Home</a>
          </li>
          <li class="breadcrumb-item active"> Dashboard</li>
        </ol>
      </nav>
    </div>
  </section>

  <section id="dashboard" class="py-4">
    <div class="container">
      <div class="row">
        <div class="col-md-12">
          <h2>Welcome {% if user.first_name %}{{ user.first_name }}{% else %}User#{{ user.id }}{% endif %}</h2>
          {% if contacts %}
          <p>Here are the property listings that you have inquired about</p>
            <table class="table">
              <thead>
                <tr>
                  <th scope="col">#</th>
                  <th scope="col">Property</th>
                  <th scope="col">Date</th>
                  <th></th>
                </tr>
              </thead>
              <tbody>
                {% for contact in contacts %}
                  <tr>
                    <td>{{ forloop.counter }}</td>
                    <td>{{ contact.listing }}</td>
                    <td>{{ contact.contact_date }}</td>
                    <td>
                      <a class="btn btn-light py-0" href="{% url 'listings:listing' contact.listing_id %}">View Listing</a>
                    </td>
                  </tr>
                {% endfor %}
              </tbody>
            </table>
          {% else %}
            <table class="table">
              <tr>
                <td>You don't have any inquiry</td>
              </tr>
            </table>
          {% endif %}
        </div>
      </div>
    </div>
  </section>
{% endblock %}

templates/accounts/login.html
{% extends 'base.html' %}

{% block title %}| Login{% endblock %}

{% block content %}
<section id="login" class="bg-light py-5">
    <div class="container">
      <div class="row">
        <div class="col-md-6 mx-auto">
          <div class="card">
            <div class="card-header bg-primary text-white">
              <h4 class="mt-2">
                <i class="fas fa-sign-in-alt"></i> Login</h4>
            </div>
            <div class="card-body">
            <!--Alerts-->
            {% include 'partials/_alerts.html' %}
              <form action="{% url 'accounts:login' %}" method="POST">
                {% csrf_token %}
                <div class="form-group">
                  <label for="username">Username</label>
                  <input type="text" name="username" class="form-control" required>
                </div>

                <div class="form-group">
                  <label for="password">Password</label>
                  <input type="password" name="password" class="form-control" required>
                </div>
                <div class="form-group">
                    <p>Don't have an account? <a href="{% url 'accounts:register' %}">Sign up</a></p>
                </div>
                <input type="submit" value="Login" class="btn btn-secondary btn-block">
              </form>
            </div>
          </div>
        </div>
      </div>
    </div>
</section>
{% endblock %}

templates/accounts/register.html
{% extends 'base.html' %}

{% block title %}| Register{% endblock %}

{% block content %}
    <section id="register" class="bg-light py-5">
        <div class="container">
            <div class="row">
                <div class="col-md-6 mx-auto">
                    <div class="card">
                        <div class="card-header bg-primary text-white">
                            <h4 class="mt-2"><i class="fas fa-user-plus"></i> Register</h4>
                        </div>
                        <div class="card-body">
                            <!--Alerts-->
                            {% include 'partials/_alerts.html' %}
                            <form action="{% url 'accounts:register' %}" method="POST">
                                {% csrf_token %}
                                <div class="form-group">
                                    <label for="first_name">First Name</label>
                                    <input type="text" name="first_name" class="form-control" required>
                                </div>
                                <div class="form-group">
                                    <label for="last_name">Last Name</label>
                                    <input type="text" name="last_name" class="form-control" required>
                                </div>
                                <div class="form-group">
                                    <label for="username">Username</label>
                                    <input type="text" name="username" class="form-control" required>
                                </div>
                                <div class="form-group">
                                    <label for="email">Email</label>
                                    <input type="email" name="email" class="form-control" required>
                                </div>
                                <div class="form-group">
                                    <label for="password">Password</label>
                                    <input type="password" name="password" class="form-control" required>
                                </div>
                                <div class="form-group">
                                    <label for="password2">Confirm Password</label>
                                    <input type="password" name="password2" class="form-control" required>
                                </div>
                                <input type="submit" value="Register" class="btn btn-secondary btn-block">
                            </form>

                            <!-- <form method="POST">
                                {% csrf_token %}
                                <div class="form-group">
                                    <label for="first_name">First Name</label>
                                    {{ form.first_name }}
                                </div>
                                <div class="form-group">
                                    <label for="last_name">Last Name</label>
                                    {{ form.last_name }}
                                </div>
                                <div class="form-group">
                                    <label for="username">Username</label>
                                    {{ form.username }}
                                </div>
                                <div class="form-group">
                                    <label for="email">Email</label>
                                    {{ form.email }}
                                </div>
                                <div class="form-group">
                                    <label for="password">Password</label>
                                    {{ form.password1 }}
                                </div>
                                <div class="form-group">
                                    <label for="password2">Confirm Password</label>
                                    {{ form.password2 }}
                                </div>
                                <input type="submit" value="Register" class="btn btn-secondary btn-block">
                            </form> -->
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </section>
{% endblock %}