contacts/urls.py
from django.urls import path

from . import views

app_name = 'contact'

urlpatterns = [
    path('contact', views.contact, name='contact'),
]

listings/urls.py
from django.urls import path

from . import views

app_name = 'listings'

urlpatterns = [
    path('', views.listings, name='listings'),
    path('<int:listing_id>', views.listing, name='listing'),
    path('search', views.search, name='search')
]

pages/urls.py
from django.urls import path

from . import views

app_name = 'pages'

urlpatterns = [
    path('', views.index, name='index'),
    path('about', views.about, name='about')
]

realestate/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('', include('pages.urls', namespace='pages')),
    path('listings/', include('listings.urls', namespace='listings')),
    path('accounts/', include('accounts.urls', namespace='accounts')),
    path('contacts/', include('contacts.urls', namespace='contacts')),
    path('admin/', admin.site.urls),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

listings/models.py
from django.db import models
from datetime import datetime
from realtors.models import Realtor

class PhotoAlbum(models.Model):
    title = models.CharField(max_length=200, blank=True)
    def default(self):
        return self.photos.filter(default=True).first()

    def thumbnails(self):
        return self.photos.filter(default=False)

    def __str__(self):
        return self.title

class Photo(models.Model):
    photo = models.ImageField(upload_to='photos/%Y/%m/%d/')
    album = models.ForeignKey(PhotoAlbum, related_name='photos', on_delete=models.CASCADE)
    name = models.CharField(max_length=100, blank=True)
    default = models.BooleanField(default=False)

    def __str__(self):
        return f'{self.name}'

    def _generate_name(self):
        num = 1
        unique_name = '{}-{}'.format(self.album.title, num)
        while Photo.objects.filter(name=unique_name).exists():
            num += 1
            unique_name = '{}-{}'.format(self.album.title, num)
        return unique_name

    def save(self, *args, **kwargs):
        if not self.name:
            self.name = self._generate_name()
            if self.default:
                self.name += '- main'
        super().save(*args, **kwargs)
        
class Listing(models.Model):
    realtor = models.ForeignKey(Realtor, on_delete=models.DO_NOTHING)
    title = models.CharField(max_length=200)
    street_address = models.CharField(max_length=200)
    apt_address = models.CharField(max_length=200, blank=True)
    city = models.CharField(max_length=50)
    state = models.CharField(max_length=50)
    zip = models.CharField(max_length=20)
    description = models.TextField(blank=True)
    price = models.IntegerField()
    bedrooms = models.IntegerField()
    bathrooms = models.DecimalField(max_digits=2, decimal_places=1)
    garage = models.IntegerField(default=0)
    sqft = models.IntegerField()
    lot_size = models.DecimalField(max_digits=5, decimal_places=0)
    album = models.OneToOneField(PhotoAlbum, on_delete=models.CASCADE, blank=True, null=True)
    is_published = models.BooleanField(default=True)
    list_date = models.DateTimeField(default=datetime.now, blank=True)

    def __str__(self):
        return self.title

listings/views.py
from django.shortcuts import render, get_object_or_404
from django.http import HttpResponse
from django.core.paginator import EmptyPage, PageNotAnInteger, Paginator

from .models import Listing, PhotoAlbum, Photo
from .choices import bedroom_choices, price_choices, state_choices

# Create your views here.
def listings(request):
    listings = Listing.objects.order_by('-list_date').filter(is_published=True)
    paginator = Paginator(listings, 12)
    page = request.GET.get('page', 1)
    paged_listings = paginator.get_page(page)
    page_range = paginator.get_elided_page_range(number=page, on_each_side=1, on_ends=1)
    context = {
        'listings': paged_listings,
        'page_range': page_range
    }
    return render(request, 'listings/listings.html', context)

def listing(request, listing_id):
    listing = get_object_or_404(Listing, pk=listing_id)
    context = {
        'listing': listing
    }
    return render(request, 'listings/listing.html', context)

def search(request):
    queryset_list = Listing.objects.order_by('-list_date')

    #keywords
    if 'keywords' in request.GET:
        keywords = request.GET['keywords']
        if keywords:
            queryset_list = queryset_list.filter(description__icontains=keywords)

    #City
    if 'city' in request.GET:
        city = request.GET['city']
        if city:
            queryset_list = queryset_list.filter(city__iexact=city)

    #State
    if 'state' in request.GET:
        state = request.GET['state']
        if state:
            queryset_list = queryset_list.filter(state__iexact=state)

    #bedrooms
    if 'bedrooms' in request.GET:
        bedrooms = request.GET['bedrooms']
        if bedrooms:
            queryset_list = queryset_list.filter(bedrooms__lte=bedrooms)

    #price
    if 'price_lower' in request.GET and 'price_upper' in request.GET:
        price_lower = request.GET['price_lower']
        price_upper = request.GET['price_upper']
        if price_lower and price_upper:
            if price_lower < price_upper:
                queryset_list = queryset_list.filter(price__gte=price_lower, price__lte=price_upper)
        elif not price_lower and price_upper:
            queryset_list = queryset_list.filter(price__lte=price_upper)
        elif not price_upper and price_lower:
            queryset_list = queryset_list.filter(price__gte=price_lower)

    context = {
        'listings': queryset_list,
        'bedroom_choices': bedroom_choices,
        'price_choices': price_choices,
        'state_choices': state_choices,
        'values': request.GET
    }
    return render(request, 'listings/search.html', context)

templates/listings/listing.html
{% extends 'base.html' %}

{% load humanize %}

{% block title %}| {{ listing.title }}{% endblock %}

{% block content %}
{% include 'partials/_alerts.html' %}
    <section id="showcase-inner" class="py-5 text-white">
        <div class="container">
            <div class="row text-center">
                <div class="col-md-12">
                    <h1 class="display-4">{{ listing.title }}</h1>
                    <p class="lead">
                        <i class="fas fa-map-marker"></i> {{ listing.city }} {{ listing.state }}, {{ listing.zip }}
                    </p>
                </div>
            </div>
        </div>
    </section>

  <!-- Breadcrumb -->
  <section id="bc" class="mt-3">
    <div class="container">
      <nav>
        <ol class="breadcrumb">
          <li class="breadcrumb-item">
            <a href="{% url 'pages:index' %}">Home</a>
          </li>
          <li class="breadcrumb-item">
            <a href="{% url 'listings:listings' %}">Listings</a>
          </li>
          <li class="breadcrumb-item active">{{ listing.title }}</li>
        </ol>
      </nav>
    </div>
  </section>

  <!-- Listing -->
  <section id="listing" class="py-4">
    <div class="container">
      <a href="{% url 'listings:listings' %}" class="btn btn-light mb-4">Back To Listings</a>
      <div class="row">
        <div class="col-md-9">
          <!-- Home Main Image -->
          <img src="{{ listing.album.default.photo.url }}" alt="" class="img-main img-fluid mb-3">
          <!-- Thumbnails -->
          {% if listing.album.thumbnails %}
          <div class="row mb-5 thumbs">
            {% for photo in listing.album.thumbnails %}
                <div class="col-md-2">
                    <a href="{{ photo.photo.url }}" data-lightbox="home-images">
                        <img src="{{ photo.photo.url }}" alt="" class="img-fluid">
                    </a>
                </div>
            {% endfor %}
          </div>
          {% else %}

          {% endif %}
          <!-- Fields -->
          <div class="row mb-5 fields">
            <div class="col-md-6">
              <ul class="list-group list-group-flush">
                <li class="list-group-item text-secondary">
                  <i class="fas fa-money-bill-alt"></i> Asking Price:
                  <span class="float-right">${{ listing.price | intcomma }}</span>
                </li>
                <li class="list-group-item text-secondary">
                  <i class="fas fa-bed"></i> Bedrooms:
                  <span class="float-right">{{ listing.bedrooms }}</span>
                </li>
                <li class="list-group-item text-secondary">
                  <i class="fas fa-bath"></i> Bathrooms:
                  <span class="float-right">{{ listing.bathrooms }}</span>
                </li>
                <li class="list-group-item text-secondary">
                  <i class="fas fa-car"></i> Garage:
                  <span class="float-right">{{ listing.garage }}
                  </span>
                </li>
              </ul>
            </div>
            <div class="col-md-6">
              <ul class="list-group list-group-flush">
                <li class="list-group-item text-secondary">
                  <i class="fas fa-th-large"></i> Square Feet:
                  <span class="float-right">{{ listing.sqft | intcomma }}</span>
                </li>
                <li class="list-group-item text-secondary">
                  <i class="fas fa-square"></i> Lot Size:
                  <span class="float-right">{{ listing.lot_size | intcomma }} sqft
                  </span>
                </li>
                <li class="list-group-item text-secondary">
                  <i class="fas fa-calendar"></i> Listing Date:
                  <span class="float-right">{{ listing.list_date }}</span>
                </li>
                <li class="list-group-item text-secondary">
                  <i class="fas fa-bed"></i> Realtor:
                  <span class="float-right">{{ listing.realtor }}
                  </span>
                </li>


              </ul>
            </div>
          </div>

          <!-- Description -->
          <div class="row mb-5">
            <div class="col-md-12">
              {{ listing.description }}
            </div>
          </div>
        </div>
        <div class="col-md-3">
          <div class="card mb-3">
            <img class="card-img-top" src="{{ listing.realtor.photo.url }}" alt="">
            <div class="card-body">
              <h5 class="card-title">Property Realtor</h5>
              <h6 class="text-secondary">{{ listing.realtor }}</h6>
            </div>
          </div>
          <button class="btn-primary btn-block btn-lg" data-toggle="modal" data-target="#inquiryModal">Make An Inquiry</button>
        </div>
      </div>
    </div>
  </section>

  <!-- Inquiry Modal -->
  <div class="modal fade" id="inquiryModal" role="dialog">
    <div class="modal-dialog">
      <div class="modal-content">
        <div class="modal-header">
          <h5 class="modal-title" id="inquiryModalLabel">Make An Inquiry</h5>
          <button type="button" class="close" data-dismiss="modal">
            <span>&times;</span>
          </button>
        </div>
        <div class="modal-body">
          <form action="{% url 'contacts:contact' %}" method="POST">
            {% csrf_token %}
            {% if user.is_authenticated %}
              <input type="hidden" name="user_id" value="{{ user.id }}">
            {% else %}
              <input type="hidden" name="user_id" value="0">
            {% endif %}
            <input type="hidden" name="realtor_email" value="{{ listing.realtor.email }}">
            <input type="hidden" name="listing_id" value="{{ listing.id }}">
            <div class="form-group">
              <label for="property_name" class="col-form-label">Property:</label>
              <input type="text" name="listing" class="form-control" value="{{ listing.title }}">
            </div>
            <div class="form-group">
              <label for="name" class="col-form-label">Name:</label>
              <input type="text" name="name" class="form-control" {% if user.is_authenticated %} value="{{ user.first_name }} {{ user.last_name }}" {% endif %} required>
            </div>
            <div class="form-group">
              <label for="email" class="col-form-label">Email:</label>
              <input type="email" name="email" class="form-control" {% if user.is_authenticated %} value="{{ user.email }}" {% endif %} required>
            </div>
            <div class="form-group">
              <label for="phone" class="col-form-label">Phone:</label>
              <input type="text" name="phone" class="form-control">
            </div>
            <div class="form-group">
              <label for="message" class="col-form-label">Message:</label>
              <textarea name="message" class="form-control"></textarea>
            </div>
            <hr>
            <input type="submit" value="Send" class="btn btn-block btn-secondary">
          </form>
        </div>
      </div>
    </div>
  </div>
{% endblock %}

templates/listings/listings.html
{% extends 'base.html' %}

{% load humanize %}

{% block title %}| Browse Listings{% endblock %}

{% block content %}
<section id="showcase-inner" class="py-5 text-white">
    <div class="container">
      <div class="row text-center">
        <div class="col-md-12">
          <h1 class="display-4">Browse Our Properties</h1>
          <p class="lead">Lorem ipsum dolor sit, amet consectetur adipisicing elit. Sunt, pariatur!</p>
        </div>
      </div>
    </div>
  </section>

  <!-- Breadcrumb -->
  <section id="bc" class="mt-3">
    <div class="container">
      <nav aria-label="breadcrumb">
        <ol class="breadcrumb">
          <li class="breadcrumb-item">
            <a href="{% url 'pages:index' %}">
              <i class="fas fa-home"></i> Home</a>
          </li>
          <li class="breadcrumb-item active"> Browse Listings</li>
        </ol>
      </nav>
    </div>
  </section>

  <!-- Listings -->
  <section id="listings" class="py-4">
    <div class="container">
      <div class="row">
        {% if listings %}
          {% for listing in listings %}
            <div class="col-md-6 col-lg-4 mb-4">
              <div class="card listing-preview">
                <img class="card-img-top" src="{{ listing.album.default.photo.url }}" alt="">
                <div class="card-img-overlay">
                  <h2>
                    <span class="badge badge-secondary text-white">${{ listing.price | intcomma }}</span>
                  </h2>
                </div>
                <div class="card-body">
                  <div class="listing-heading text-center">
                    <h4 class="text-primary">{{ listing.title }}</h4>
                    <p>
                      <i class="fas fa-map-marker text-secondary"></i> {{ listing.city }} {{ listing.state }}, {{ listing.zip }}</p>
                  </div>
                  <hr>
                  <div class="row py-2 text-secondary">
                    <div class="col-6">
                      <i class="fas fa-th-large"></i> Sqft: {{ listing.sqft | intcomma }}</div>
                    <div class="col-6">
                      <i class="fas fa-car"></i> Garage: {{ listing.garage }}</div>
                  </div>
                  <div class="row py-2 text-secondary">
                    <div class="col-6">
                      <i class="fas fa-bed"></i> Bedrooms: {{ listing.bedrooms }}</div>
                    <div class="col-6">
                      <i class="fas fa-bath"></i> Bathrooms: {{ listing.bathrooms }}</div>
                  </div>
                  <hr>
                  <div class="row py-2 text-secondary">
                    <div class="col-12">
                      <i class="fas fa-user"></i> {{ listing.realtor }}</div>
                  </div>
                  <div class="row text-secondary pb-2">
                    <div class="col-6">
                      <i class="fas fa-clock"></i> {{ listing.list_date | timesince }} </div>
                  </div>
                  <hr>
                  <a href="{% url 'listings:listing' listing.id %}" class="btn btn-primary btn-block">More Info</a>
                </div>
              </div>
            </div>
          {% endfor %}
        {% else %}
          <div class="col-md-12">
            <p>No Listings Available</p>
          </div>
        {% endif %}
      </div>

      <!--Pagination-->
      <div class="row">
        <div class="col-md-12">
          {% if listings.has_other_pages %}
            <ul class="pagination">
              {% if listings.has_previous %}
                <li class="page-item">
                  <a href="?page={{ listings.previous_page_number }}" class="page-link">&laquo;</a>
                </li>
              {% else %}
                <li class="page-item disabled">
                  <a class="page-link">&laquo;</a>
                </li>
              {% endif %}

              {% for i in page_range %}
                {% if listings.number == i %}
                  <li class="page-item active">
                    <a class="page-link">{{ i }}</a>
                  </li>
                {% else %}
                  {% if i == listings.paginator.ELLIPSIS %}
                    <li class="page-item">
                      <a onclick="go_to_page({{listings.number}})" class="page-link">{{ i }}</a>
                    </li>
                  {% else %}
                    <li class="page-item">
                      <a href="?page={{ i }}" class="page-link">{{ i }}</a>
                    </li>
                  {% endif %}
                {% endif %}
              {% endfor %}

              {% if listings.has_next %}
                <li class="page-item">
                  <a href="?page={{ listings.next_page_number }}" class="page-link">&raquo;</a>
                </li>
              {% else %}
                <li class="page-item disabled">
                  <a class="page-link">&raquo;</a>
                </li>
              {% endif %}
            </ul>
          {% endif %}
        </div>
      </div>
    </div>
  </section>
{% endblock %}

{% block extrascripts %} 
  <script>
    function go_to_page(current_page){
      let destination_page = prompt("Go to page:", current_page);
      if (destination_page == null || destination_page == "" || isNaN(destination_page)){
        //do nothing
      }
      else{
        location.href = "?page=" + destination_page;
      }
    }
  </script>
{% endblock %}

templates/listings/search.html
{% extends 'base.html' %}

{% load humanize %}

{% block title %}| Search{% endblock %}

{% block content %}
<section id="showcase-inner" class="showcase-search text-white py-5">
    <div class="container">
      <div class="row text-center">
        <div class="col-md-12">
          <form action="{% url 'listings:search' %}">
            <!-- Form Row 1 -->
            <div class="form-row">
              <div class="col-md-4 mb-3">
                <label class="sr-only">Keywords</label>
                <input type="text" name="keywords" class="form-control" value="{{ values.keywords }}" placeholder="Keyword (Pool, Garage, etc)">
              </div>

              <div class="col-md-4 mb-3">
                <label class="sr-only">City</label>
                <input type="text" name="city" class="form-control" value="{{ values.city }}" placeholder="City">
              </div>

              <div class="col-md-4 mb-3">
                <label class="sr-only">State</label>
                <select name="state" class="form-control">
                  <option selected="true" value="">State (All)</option>
                    {% for k, v in state_choices.items %}
                        <option value="{{ k }}" {% if k == values.state %} selected {% endif %}>{{ v }}</option>
                    {% endfor %}
                </select>
              </div>
            </div>
            <!-- Form Row 2 -->
            <div class="form-row">
              <div class="col-md-6 mb-3">
                <label class="sr-only">Bedrooms</label>
                <select name="bedrooms" class="form-control">
                  <option selected="true" value="">Bedrooms (Any)</option>
                    {% for k, v in bedroom_choices.items %}
                      <option value="{{ k }}" {% if k == values.bedrooms %} selected {% endif %} >{{ v }}</option>
                    {% endfor %}
                </select>
              </div>
              <div class="col-md-3 mb-3">
                <select name="price_lower" class="form-control">
                  <option selected="true" value="">Min Price (All)</option>
                    {% for k, v in price_choices.items %}
                      <option value="{{ k }}" {% if k == values.price_lower %} selected {% endif %} >{{ v }}</option>
                    {% endfor %}
                </select>
              </div>
              <div class="col-md-3 mb-3">
                <select name="price_upper" class="form-control">
                  <option selected="true" value="">Max Price (All)</option>
                    {% for k, v in price_choices.items %}
                      <option value="{{ k }}" {% if k == values.price_upper %} selected {% endif %} >{{ v }}</option>
                    {% endfor %}
                </select>
              </div>
            </div>
            <button class="btn btn-secondary btn-block mt-4" type="submit">Submit form</button>
          </form>
        </div>
      </div>
    </div>
  </section>

  <!-- Breadcrumb -->
  <section id="bc" class="mt-3">
    <div class="container">
      <nav aria-label="breadcrumb">
        <ol class="breadcrumb">
          <li class="breadcrumb-item">
            <a href="{% url 'pages:index' %}">
              <i class="fas fa-home"></i> Home</a>
          </li>
          <li class="breadcrumb-item">
            <a href="{% url 'listings:listings' %}">Browse Listings</a>
          </li>
          <li class="breadcrumb-item active"> Search Results</li>
        </ol>
      </nav>
    </div>
  </section>

  <!-- Listings -->
  <section id="listings" class="py-4">
    <div class="container">
        <div class="row">
            {% if listings %}
              {% for listing in listings %}
                <div class="col-md-6 col-lg-4 mb-4">
                  <div class="card listing-preview">
                    <img class="card-img-top" src="{{ listing.album.default.photo.url }}" alt="">
                    <div class="card-img-overlay">
                      <h2>
                        <span class="badge badge-secondary text-white">${{ listing.price | intcomma }}</span>
                      </h2>
                    </div>
                    <div class="card-body">
                      <div class="listing-heading text-center">
                        <h4 class="text-primary">{{ listing.title }}</h4>
                        <p>
                          <i class="fas fa-map-marker text-secondary"></i> {{ listing.city }} {{ listing.state }}, {{ listing.zip }}</p>
                      </div>
                      <hr>
                      <div class="row py-2 text-secondary">
                        <div class="col-6">
                          <i class="fas fa-th-large"></i> Sqft: {{ listing.sqft | intcomma }}</div>
                        <div class="col-6">
                          <i class="fas fa-car"></i> Garage: {{ listing.garage }}</div>
                      </div>
                      <div class="row py-2 text-secondary">
                        <div class="col-6">
                          <i class="fas fa-bed"></i> Bedrooms: {{ listing.bedrooms }}</div>
                        <div class="col-6">
                          <i class="fas fa-bath"></i> Bathrooms: {{ listing.bathrooms }}</div>
                      </div>
                      <hr>
                      <div class="row py-2 text-secondary">
                        <div class="col-12">
                          <i class="fas fa-user"></i> {{ listing.realtor }}</div>
                      </div>
                      <div class="row text-secondary pb-2">
                        <div class="col-6">
                          <i class="fas fa-clock"></i> {{ listing.list_date | timesince }} </div>
                      </div>
                      <hr>
                      <a href="{% url 'listings:listing' listing.id %}" class="btn btn-primary btn-block">More Info</a>
                    </div>
                  </div>
                </div>
              {% endfor %}
            {% else %}
              <div class="col-md-12">
                <p>No Listings Available</p>
              </div>
            {% endif %}
        </div>
    </div>
  </section>
{% endblock %}